M48
; DRILL file {KiCad 9.0.6} date 2025-11-11T22:46:27-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-11T22:46:27-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X167.91Y-83.315
X173.69Y-83.315
T2
X207.634Y-89.14
X208.65Y-84.06
X209.666Y-89.14
M30
